# Generated by Django 3.1 on 2020-08-12 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['-datetime']},
        ),
        migrations.RenameField(
            model_name='event',
            old_name='end_date',
            new_name='final_date',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='start_date',
            new_name='initial_date',
        ),
    ]
