# Generated by Django 3.1 on 2020-08-12 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20200812_0553'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='address',
            new_name='event_address',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='name',
            new_name='event_category',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='final_date',
            new_name='event_final_date',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='initial_date',
            new_name='event_initial_date',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='category',
            new_name='event_name',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='place',
            new_name='event_place',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='type',
            new_name='event_type',
        ),
    ]
