# Generated by Django 3.1 on 2020-08-18 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_auto_20200812_0727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_final_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_initial_date',
            field=models.DateField(),
        ),
    ]
